server:
  host: "0.0.0.0"
  port: 8080

redis:
  address: "127.0.0.1:6379"
  password: ""
  database: 0
  cluster_mode: false

kafka:
  brokers:
    - "127.0.0.1:9094"
  topic: "application-logs"
  group_id: "alert-engine-e2e-fresh-20250716"
  consumer:
    min_bytes: 1024
    max_bytes: 1048576
    max_wait: "2s"
    start_offset: -2

# CRITICAL: Log processing configuration
log_processing:
  batch_size: 50
  flush_interval: "10s"
  validation:
    default_log_level: "INFO"  # Default level for missing log levels

# CRITICAL: Alert processing configuration  
alerting:
  default_time_window: "5m"
  default_threshold: 1  # Lower threshold for testing

# CRITICAL: Notification settings
notifications:
  enabled: true
  
  # Slack notification configuration
  slack:
    webhook_url: ""           # Set via environment variable SLACK_WEBHOOK_URL
    channel: "#test-mp-channel"
    username: "Alert Engine (E2E)"
    icon_emoji: ":warning:"
    timeout: 30s


  # Configurable alert message template
  templates:
    alert_message: |
      🚨 Alert: {{.RuleName}}
      Service: {{.Service}}
      Namespace: {{.Namespace}}
      Level: {{.Level}}
      Count: {{.Count}} in {{.TimeWindow}}
      Message: {{.Message}}
    
    slack_alert_title: "{{.SeverityEmoji}} {{.RuleName}}"
    
    slack_alert_fields:
      - title: "Severity"
        value: "{{.Severity}}"
        short: true
      - title: "Namespace" 
        value: "{{.Namespace}}"
        short: true
      - title: "Service"
        value: "{{.Service}}"
        short: true
      - title: "Pod"
        value: "{{.Pod}}"
        short: true
      - title: "Log Level"
        value: "{{.Level}}"
        short: true
      - title: "Count"
        value: "{{.Count}}"
        short: true

  # Configurable severity mappings
  severity:
    emojis:
      critical: "🔴"
      high: "🟠"
      medium: "🟡"
      low: "🟢"
      default: "⚪"
    
    colors:
      critical: "#ff0000"
      high: "#ff8000"
      medium: "#ffff00"
      low: "#00ff00"
      default: "#808080"

# Default rules configuration for E2E testing
default_rules:
  enabled: false
