version: '3.8'

services:
  # Zookeeper for Kafka
  zookeeper-e2e:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper-e2e
    container_name: alert-engine-zookeeper-e2e
    ports:
      - "2182:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - alert-engine-e2e
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Kafka for log ingestion
  kafka-e2e:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka-e2e
    container_name: alert-engine-kafka-e2e
    depends_on:
      zookeeper-e2e:
        condition: service_healthy
    ports:
      - "9094:9094"
      - "9102:9102"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-e2e:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-e2e:29092,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_RETENTION_BYTES: 1073741824
      KAFKA_LOG_SEGMENT_BYTES: 268435456
      KAFKA_LOG_CLEANUP_POLICY: delete
      KAFKA_CONSUMER_SESSION_TIMEOUT_MS: 30000
      KAFKA_CONSUMER_HEARTBEAT_INTERVAL_MS: 3000
    networks:
      - alert-engine-e2e
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9094"]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - kafka-e2e-data:/var/lib/kafka/data

  # Redis for state storage
  redis-e2e:
    image: redis:7-alpine
    hostname: redis-e2e
    container_name: alert-engine-redis-e2e
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - alert-engine-e2e
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis-e2e-data:/data

  # Kafka UI for debugging (optional)
  kafka-ui-e2e:
    image: provectuslabs/kafka-ui:latest
    hostname: kafka-ui-e2e
    container_name: alert-engine-kafka-ui-e2e
    depends_on:
      kafka-e2e:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-e2e
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-e2e:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper-e2e:2181
    networks:
      - alert-engine-e2e
    profiles:
      - debug

  # Redis Commander for debugging (optional)
  redis-commander-e2e:
    image: rediscommander/redis-commander:latest
    hostname: redis-commander-e2e
    container_name: alert-engine-redis-commander-e2e
    depends_on:
      redis-e2e:
        condition: service_healthy
    ports:
      - "8082:8081"
    environment:
      REDIS_HOSTS: local-e2e:redis-e2e:6379:0:e2epass
    networks:
      - alert-engine-e2e
    profiles:
      - debug

networks:
  alert-engine-e2e:
    name: alert-engine-e2e
    driver: bridge

volumes:
  kafka-e2e-data:
    name: alert-engine-kafka-e2e-data
  redis-e2e-data:
    name: alert-engine-redis-e2e-data 