apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: mock-log-generator
  annotations:
    description: "MockLogGenerator deployment for Alert Engine testing"

# Target namespace
namespace: mock-logs

# Common labels applied to all resources
commonLabels:
  app: mock-log-generator
  component: log-generator
  version: v1.0.0
  managed-by: kustomize

# Common annotations applied to all resources
commonAnnotations:
  description: "Mock Log Generator for Alert Engine testing - outputs logs to stdout"
  contact: "alert-engine-team"
  documentation: "https://github.com/your-org/alert-engine/blob/main/deployments/mock/README.md"

# Resources to include
resources:
- configmap.yaml
- serviceaccount.yaml
- networkpolicy.yaml
- deployment.yaml

# Image transformations (update the image tag)
images:
- name: quay.io/alert-engine/mock-log-generator
  newTag: latest

# Resource transformations
replicas:
- name: mock-log-generator
  count: 1

# Patches for environment-specific customizations
patchesStrategicMerge:
# Uncomment and customize for different environments
#- patches/development.yaml
#- patches/production.yaml

# JSON patches for specific modifications
patches:
# Example: Increase resources for production
#- target:
#    kind: Deployment
#    name: mock-log-generator
#  patch: |-
#    - op: replace
#      path: /spec/template/spec/containers/0/resources/limits/memory
#      value: 512Mi
#    - op: replace
#      path: /spec/template/spec/containers/0/resources/limits/cpu
#      value: 300m

# Configuration generators
configMapGenerator:
# Example: Generate ConfigMap from environment files
#- name: mock-log-generator-env-config
#  files:
#  - .env

# Secret generators  
secretGenerator:
# Example: Generate secrets from files (not needed for simple log generator)
#- name: mock-log-generator-secrets
#  files:
#  - credentials.txt

# Resource ordering
# Ensures resources are applied in the correct order
# (ServiceAccount and ConfigMap before Deployment)

# Validation
# Kustomize will validate the final output 